/**
 * Georgia Counties Seed Data
 *
 * Contains all 159 Georgia counties with FIPS codes from US Census Bureau.
 * Reference: https://www.census.gov/library/reference/code-lists/ansi.html
 *
 * FIPS Code Format: 5 digits = State (2) + County (3)
 * Georgia State FIPS: 13
 * Example: Fulton County = 13121 (13 + 121)
 *
 * @enterprise-standards
 * - DB-006: Geographic reference data for tenant scoping
 * - SEC-006: Static data, no SQL injection risk
 */

export interface CountyData {
  name: string;
  fips_code: string;
  county_seat?: string;
  population?: number;
}

/**
 * All 159 Georgia Counties
 * Sorted alphabetically by name
 * Data source: US Census Bureau FIPS codes
 */
export const georgiaCounties: CountyData[] = [
  { name: "Appling", fips_code: "13001" },
  { name: "Atkinson", fips_code: "13003" },
  { name: "Bacon", fips_code: "13005" },
  { name: "Baker", fips_code: "13007" },
  { name: "Baldwin", fips_code: "13009" },
  { name: "Banks", fips_code: "13011" },
  { name: "Barrow", fips_code: "13013" },
  { name: "Bartow", fips_code: "13015" },
  { name: "Ben Hill", fips_code: "13017" },
  { name: "Berrien", fips_code: "13019" },
  { name: "Bibb", fips_code: "13021" },
  { name: "Bleckley", fips_code: "13023" },
  { name: "Brantley", fips_code: "13025" },
  { name: "Brooks", fips_code: "13027" },
  { name: "Bryan", fips_code: "13029" },
  { name: "Bulloch", fips_code: "13031" },
  { name: "Burke", fips_code: "13033" },
  { name: "Butts", fips_code: "13035" },
  { name: "Calhoun", fips_code: "13037" },
  { name: "Camden", fips_code: "13039" },
  { name: "Candler", fips_code: "13043" },
  { name: "Carroll", fips_code: "13045" },
  { name: "Catoosa", fips_code: "13047" },
  { name: "Charlton", fips_code: "13049" },
  { name: "Chatham", fips_code: "13051" },
  { name: "Chattahoochee", fips_code: "13053" },
  { name: "Chattooga", fips_code: "13055" },
  { name: "Cherokee", fips_code: "13057" },
  { name: "Clarke", fips_code: "13059" },
  { name: "Clay", fips_code: "13061" },
  { name: "Clayton", fips_code: "13063" },
  { name: "Clinch", fips_code: "13065" },
  { name: "Cobb", fips_code: "13067" },
  { name: "Coffee", fips_code: "13069" },
  { name: "Colquitt", fips_code: "13071" },
  { name: "Columbia", fips_code: "13073" },
  { name: "Cook", fips_code: "13075" },
  { name: "Coweta", fips_code: "13077" },
  { name: "Crawford", fips_code: "13079" },
  { name: "Crisp", fips_code: "13081" },
  { name: "Dade", fips_code: "13083" },
  { name: "Dawson", fips_code: "13085" },
  { name: "Decatur", fips_code: "13087" },
  { name: "DeKalb", fips_code: "13089" },
  { name: "Dodge", fips_code: "13091" },
  { name: "Dooly", fips_code: "13093" },
  { name: "Dougherty", fips_code: "13095" },
  { name: "Douglas", fips_code: "13097" },
  { name: "Early", fips_code: "13099" },
  { name: "Echols", fips_code: "13101" },
  { name: "Effingham", fips_code: "13103" },
  { name: "Elbert", fips_code: "13105" },
  { name: "Emanuel", fips_code: "13107" },
  { name: "Evans", fips_code: "13109" },
  { name: "Fannin", fips_code: "13111" },
  { name: "Fayette", fips_code: "13113" },
  { name: "Floyd", fips_code: "13115" },
  { name: "Forsyth", fips_code: "13117" },
  { name: "Franklin", fips_code: "13119" },
  { name: "Fulton", fips_code: "13121" },
  { name: "Gilmer", fips_code: "13123" },
  { name: "Glascock", fips_code: "13125" },
  { name: "Glynn", fips_code: "13127" },
  { name: "Gordon", fips_code: "13129" },
  { name: "Grady", fips_code: "13131" },
  { name: "Greene", fips_code: "13133" },
  { name: "Gwinnett", fips_code: "13135" },
  { name: "Habersham", fips_code: "13137" },
  { name: "Hall", fips_code: "13139" },
  { name: "Hancock", fips_code: "13141" },
  { name: "Haralson", fips_code: "13143" },
  { name: "Harris", fips_code: "13145" },
  { name: "Hart", fips_code: "13147" },
  { name: "Heard", fips_code: "13149" },
  { name: "Henry", fips_code: "13151" },
  { name: "Houston", fips_code: "13153" },
  { name: "Irwin", fips_code: "13155" },
  { name: "Jackson", fips_code: "13157" },
  { name: "Jasper", fips_code: "13159" },
  { name: "Jeff Davis", fips_code: "13161" },
  { name: "Jefferson", fips_code: "13163" },
  { name: "Jenkins", fips_code: "13165" },
  { name: "Johnson", fips_code: "13167" },
  { name: "Jones", fips_code: "13169" },
  { name: "Lamar", fips_code: "13171" },
  { name: "Lanier", fips_code: "13173" },
  { name: "Laurens", fips_code: "13175" },
  { name: "Lee", fips_code: "13177" },
  { name: "Liberty", fips_code: "13179" },
  { name: "Lincoln", fips_code: "13181" },
  { name: "Long", fips_code: "13183" },
  { name: "Lowndes", fips_code: "13185" },
  { name: "Lumpkin", fips_code: "13187" },
  { name: "Macon", fips_code: "13193" },
  { name: "Madison", fips_code: "13195" },
  { name: "Marion", fips_code: "13197" },
  { name: "McDuffie", fips_code: "13189" },
  { name: "McIntosh", fips_code: "13191" },
  { name: "Meriwether", fips_code: "13199" },
  { name: "Miller", fips_code: "13201" },
  { name: "Mitchell", fips_code: "13205" },
  { name: "Monroe", fips_code: "13207" },
  { name: "Montgomery", fips_code: "13209" },
  { name: "Morgan", fips_code: "13211" },
  { name: "Murray", fips_code: "13213" },
  { name: "Muscogee", fips_code: "13215" },
  { name: "Newton", fips_code: "13217" },
  { name: "Oconee", fips_code: "13219" },
  { name: "Oglethorpe", fips_code: "13221" },
  { name: "Paulding", fips_code: "13223" },
  { name: "Peach", fips_code: "13225" },
  { name: "Pickens", fips_code: "13227" },
  { name: "Pierce", fips_code: "13229" },
  { name: "Pike", fips_code: "13231" },
  { name: "Polk", fips_code: "13233" },
  { name: "Pulaski", fips_code: "13235" },
  { name: "Putnam", fips_code: "13237" },
  { name: "Quitman", fips_code: "13239" },
  { name: "Rabun", fips_code: "13241" },
  { name: "Randolph", fips_code: "13243" },
  { name: "Richmond", fips_code: "13245" },
  { name: "Rockdale", fips_code: "13247" },
  { name: "Schley", fips_code: "13249" },
  { name: "Screven", fips_code: "13251" },
  { name: "Seminole", fips_code: "13253" },
  { name: "Spalding", fips_code: "13255" },
  { name: "Stephens", fips_code: "13257" },
  { name: "Stewart", fips_code: "13259" },
  { name: "Sumter", fips_code: "13261" },
  { name: "Talbot", fips_code: "13263" },
  { name: "Taliaferro", fips_code: "13265" },
  { name: "Tattnall", fips_code: "13267" },
  { name: "Taylor", fips_code: "13269" },
  { name: "Telfair", fips_code: "13271" },
  { name: "Terrell", fips_code: "13273" },
  { name: "Thomas", fips_code: "13275" },
  { name: "Tift", fips_code: "13277" },
  { name: "Toombs", fips_code: "13279" },
  { name: "Towns", fips_code: "13281" },
  { name: "Treutlen", fips_code: "13283" },
  { name: "Troup", fips_code: "13285" },
  { name: "Turner", fips_code: "13287" },
  { name: "Twiggs", fips_code: "13289" },
  { name: "Union", fips_code: "13291" },
  { name: "Upson", fips_code: "13293" },
  { name: "Walker", fips_code: "13295" },
  { name: "Walton", fips_code: "13297" },
  { name: "Ware", fips_code: "13299" },
  { name: "Warren", fips_code: "13301" },
  { name: "Washington", fips_code: "13303" },
  { name: "Wayne", fips_code: "13305" },
  { name: "Webster", fips_code: "13307" },
  { name: "Wheeler", fips_code: "13309" },
  { name: "White", fips_code: "13311" },
  { name: "Whitfield", fips_code: "13313" },
  { name: "Wilcox", fips_code: "13315" },
  { name: "Wilkes", fips_code: "13317" },
  { name: "Wilkinson", fips_code: "13319" },
  { name: "Worth", fips_code: "13321" },
];

/**
 * Major Georgia cities with county associations
 * Used for initial seeding and ZIP code lookups
 */
export const georgiaCities = [
  { name: "Atlanta", county: "Fulton" },
  { name: "Augusta", county: "Richmond" },
  { name: "Columbus", county: "Muscogee" },
  { name: "Macon", county: "Bibb" },
  { name: "Savannah", county: "Chatham" },
  { name: "Athens", county: "Clarke" },
  { name: "Sandy Springs", county: "Fulton" },
  { name: "Roswell", county: "Fulton" },
  { name: "Johns Creek", county: "Fulton" },
  { name: "Warner Robins", county: "Houston" },
  { name: "Alpharetta", county: "Fulton" },
  { name: "Marietta", county: "Cobb" },
  { name: "Valdosta", county: "Lowndes" },
  { name: "Smyrna", county: "Cobb" },
  { name: "Dunwoody", county: "DeKalb" },
  { name: "Brookhaven", county: "DeKalb" },
  { name: "Peachtree City", county: "Fayette" },
  { name: "Gainesville", county: "Hall" },
  { name: "Newnan", county: "Coweta" },
  { name: "Dalton", county: "Whitfield" },
];

/**
 * Sample Georgia ZIP codes for initial seeding
 * Full ZIP code data should be loaded from US Census ZCTA files
 */
export const georgiaZipCodes = [
  // Atlanta Metro
  { zip_code: "30301", city_name: "Atlanta", county: "Fulton" },
  { zip_code: "30302", city_name: "Atlanta", county: "Fulton" },
  { zip_code: "30303", city_name: "Atlanta", county: "Fulton" },
  { zip_code: "30305", city_name: "Atlanta", county: "Fulton" },
  { zip_code: "30306", city_name: "Atlanta", county: "Fulton" },
  { zip_code: "30307", city_name: "Atlanta", county: "DeKalb" },
  { zip_code: "30308", city_name: "Atlanta", county: "Fulton" },
  { zip_code: "30309", city_name: "Atlanta", county: "Fulton" },
  { zip_code: "30310", city_name: "Atlanta", county: "Fulton" },
  { zip_code: "30311", city_name: "Atlanta", county: "Fulton" },
  { zip_code: "30312", city_name: "Atlanta", county: "Fulton" },
  { zip_code: "30313", city_name: "Atlanta", county: "Fulton" },
  { zip_code: "30314", city_name: "Atlanta", county: "Fulton" },
  { zip_code: "30315", city_name: "Atlanta", county: "Fulton" },
  { zip_code: "30316", city_name: "Atlanta", county: "DeKalb" },
  { zip_code: "30317", city_name: "Atlanta", county: "DeKalb" },
  { zip_code: "30318", city_name: "Atlanta", county: "Fulton" },
  { zip_code: "30319", city_name: "Atlanta", county: "DeKalb" },
  { zip_code: "30324", city_name: "Atlanta", county: "Fulton" },
  { zip_code: "30326", city_name: "Atlanta", county: "Fulton" },
  { zip_code: "30327", city_name: "Atlanta", county: "Fulton" },
  { zip_code: "30328", city_name: "Atlanta", county: "Fulton" },
  { zip_code: "30329", city_name: "Atlanta", county: "DeKalb" },
  { zip_code: "30331", city_name: "Atlanta", county: "Fulton" },
  { zip_code: "30332", city_name: "Atlanta", county: "Fulton" },
  { zip_code: "30334", city_name: "Atlanta", county: "Fulton" },
  { zip_code: "30336", city_name: "Atlanta", county: "Fulton" },
  { zip_code: "30337", city_name: "Atlanta", county: "Fulton" },
  { zip_code: "30338", city_name: "Atlanta", county: "DeKalb" },
  { zip_code: "30339", city_name: "Atlanta", county: "Cobb" },
  { zip_code: "30340", city_name: "Atlanta", county: "DeKalb" },
  { zip_code: "30341", city_name: "Atlanta", county: "DeKalb" },
  { zip_code: "30342", city_name: "Atlanta", county: "Fulton" },
  { zip_code: "30344", city_name: "Atlanta", county: "Fulton" },
  { zip_code: "30345", city_name: "Atlanta", county: "DeKalb" },
  { zip_code: "30346", city_name: "Atlanta", county: "DeKalb" },
  { zip_code: "30349", city_name: "Atlanta", county: "Fulton" },
  { zip_code: "30350", city_name: "Atlanta", county: "Fulton" },
  // Marietta/Cobb County
  { zip_code: "30060", city_name: "Marietta", county: "Cobb" },
  { zip_code: "30062", city_name: "Marietta", county: "Cobb" },
  { zip_code: "30064", city_name: "Marietta", county: "Cobb" },
  { zip_code: "30066", city_name: "Marietta", county: "Cobb" },
  { zip_code: "30067", city_name: "Marietta", county: "Cobb" },
  { zip_code: "30068", city_name: "Marietta", county: "Cobb" },
  // Savannah
  { zip_code: "31401", city_name: "Savannah", county: "Chatham" },
  { zip_code: "31404", city_name: "Savannah", county: "Chatham" },
  { zip_code: "31405", city_name: "Savannah", county: "Chatham" },
  { zip_code: "31406", city_name: "Savannah", county: "Chatham" },
  { zip_code: "31410", city_name: "Savannah", county: "Chatham" },
  // Augusta
  { zip_code: "30901", city_name: "Augusta", county: "Richmond" },
  { zip_code: "30904", city_name: "Augusta", county: "Richmond" },
  { zip_code: "30906", city_name: "Augusta", county: "Richmond" },
  { zip_code: "30909", city_name: "Augusta", county: "Richmond" },
  // Columbus
  { zip_code: "31901", city_name: "Columbus", county: "Muscogee" },
  { zip_code: "31904", city_name: "Columbus", county: "Muscogee" },
  { zip_code: "31906", city_name: "Columbus", county: "Muscogee" },
  // Macon
  { zip_code: "31201", city_name: "Macon", county: "Bibb" },
  { zip_code: "31204", city_name: "Macon", county: "Bibb" },
  { zip_code: "31206", city_name: "Macon", county: "Bibb" },
  { zip_code: "31210", city_name: "Macon", county: "Bibb" },
];
