/**
 * Integration Tests: Report Page Date Display
 *
 * ============================================================================
 * TRACEABILITY MATRIX
 * ============================================================================
 *
 * | Test ID              | Component                  | Requirement              | Bug Fixed                    |
 * |----------------------|----------------------------|--------------------------|------------------------------|
 * | RPD-INT-001          | daily/page.tsx             | FE-005: UI_SECURITY      | extractDayFromBusinessDate   |
 * | RPD-INT-002          | weekly/page.tsx            | FE-005: UI_SECURITY      | formatBusinessDate           |
 * | RPD-INT-003          | monthly/page.tsx           | FE-005: UI_SECURITY      | formatBusinessDate           |
 * | RPD-INT-004          | All report pages           | SEC-004: XSS             | Input sanitization           |
 * | RPD-INT-005          | All report pages           | SEC-014: INPUT_VALIDATION| Invalid date handling        |
 *
 * ============================================================================
 * TEST PYRAMID COMPLIANCE
 * ============================================================================
 *
 * This file implements INTEGRATION TESTS (middle of pyramid):
 * - Tests real data flow between utilities and components
 * - Uses actual date-format.utils.ts functions
 * - Validates end-to-end date transformation
 * - No external API calls (fast execution)
 *
 * ============================================================================
 * BUG DOCUMENTATION
 * ============================================================================
 *
 * Fixed bugs (2026-01-06):
 *
 * 1. daily/page.tsx:194 - Calendar day extraction bug
 *    BEFORE: const dayNumber = new Date(date).getDate();
 *    AFTER:  const dayNumber = extractDayFromBusinessDate(date) ?? 1;
 *
 * 2. weekly/page.tsx:270 - Date display bug
 *    BEFORE: new Date(day.business_date).toLocaleDateString(...)
 *    AFTER:  formatBusinessDate(day.business_date, "EEE, MMM d")
 *
 * 3. monthly/page.tsx:331 - Date display bug
 *    BEFORE: new Date(day.business_date).toLocaleDateString(...)
 *    AFTER:  formatBusinessDate(day.business_date, "EEE, MMM d")
 */

import { describe, it, expect } from "vitest";
import {
  formatBusinessDate,
  extractDayFromBusinessDate,
  isValidBusinessDate,
} from "../../src/utils/date-format.utils";

// ============================================================================
// TEST DATA
// ============================================================================

/**
 * Simulates API response from day-summaries endpoint
 * business_date is returned as YYYY-MM-DD string
 */
interface MockDaySummary {
  business_date: string;
  net_sales: number;
  transaction_count: number;
  shift_count: number;
  variance_amount: number;
}

const createMockDaySummary = (
  overrides: Partial<MockDaySummary> = {},
): MockDaySummary => ({
  business_date: "2026-01-06",
  net_sales: 1500.0,
  transaction_count: 45,
  shift_count: 3,
  variance_amount: -5.5,
  ...overrides,
});

/**
 * Simulates calendar date strings generated by daily/page.tsx
 */
const generateCalendarDates = (year: number, month: number): string[] => {
  const daysInMonth = new Date(year, month + 1, 0).getDate();
  return Array.from({ length: daysInMonth }, (_, i) => {
    const day = i + 1;
    return `${year}-${String(month + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
  });
};

// ============================================================================
// DAILY PAGE INTEGRATION TESTS
// ============================================================================

describe("RPD-INT: Daily Reports Page Date Integration", () => {
  describe("RPD-INT-001: Calendar Day Extraction (Bug Fix Verification)", () => {
    /**
     * Verifies the fix for daily/page.tsx:194
     * The calendar grid must display correct day numbers
     */
    it("should extract correct day for each date in January 2026", () => {
      const janDates = generateCalendarDates(2026, 0);

      janDates.forEach((date, index) => {
        const expectedDay = index + 1;
        const actualDay = extractDayFromBusinessDate(date);

        expect(actualDay).toBe(expectedDay);
        // Explicit regression check for the original bug
        expect(actualDay).not.toBe(expectedDay - 1);
      });
    });

    it("should extract day 6 from 2026-01-06 (original bug case)", () => {
      // This was the specific date that exposed the bug
      const date = "2026-01-06";
      const dayNumber = extractDayFromBusinessDate(date);

      expect(dayNumber).toBe(6);
      expect(dayNumber).not.toBe(5); // Bug would show 5
    });

    it("should handle year boundary dates correctly", () => {
      // Jan 1 should display as 1, not 31
      expect(extractDayFromBusinessDate("2026-01-01")).toBe(1);
      // Dec 31 should display as 31
      expect(extractDayFromBusinessDate("2025-12-31")).toBe(31);
    });

    it("should handle February 29 in leap years", () => {
      expect(extractDayFromBusinessDate("2024-02-29")).toBe(29);
    });

    it("should return null for invalid dates (used for fallback)", () => {
      // The pattern in daily/page.tsx: extractDayFromBusinessDate(date) ?? 1
      const invalidDayNumber = extractDayFromBusinessDate("invalid") ?? 1;
      expect(invalidDayNumber).toBe(1);
    });
  });

  describe("RPD-INT-002: Calendar Grid Date Generation", () => {
    it("should generate correct dates for January 2026", () => {
      const dates = generateCalendarDates(2026, 0);

      expect(dates.length).toBe(31);
      expect(dates[0]).toBe("2026-01-01");
      expect(dates[5]).toBe("2026-01-06"); // The bug case
      expect(dates[30]).toBe("2026-01-31");
    });

    it("should generate correct dates for February (leap year)", () => {
      const dates = generateCalendarDates(2024, 1);

      expect(dates.length).toBe(29);
      expect(dates[28]).toBe("2024-02-29");
    });

    it("should generate valid business dates for all days", () => {
      const dates = generateCalendarDates(2026, 0);

      dates.forEach((date) => {
        expect(isValidBusinessDate(date)).toBe(true);
      });
    });
  });
});

// ============================================================================
// WEEKLY PAGE INTEGRATION TESTS
// ============================================================================

describe("RPD-INT: Weekly Reports Page Date Integration", () => {
  describe("RPD-INT-003: Daily Breakdown Date Formatting (Bug Fix Verification)", () => {
    /**
     * Verifies the fix for weekly/page.tsx:270
     * Daily breakdown table must show correct dates
     */
    it("should format business dates correctly for weekly breakdown", () => {
      const weekData: MockDaySummary[] = [
        createMockDaySummary({ business_date: "2026-01-05" }),
        createMockDaySummary({ business_date: "2026-01-06" }),
        createMockDaySummary({ business_date: "2026-01-07" }),
        createMockDaySummary({ business_date: "2026-01-08" }),
        createMockDaySummary({ business_date: "2026-01-09" }),
        createMockDaySummary({ business_date: "2026-01-10" }),
        createMockDaySummary({ business_date: "2026-01-11" }),
      ];

      const formattedDates = weekData.map((day) =>
        formatBusinessDate(day.business_date, "EEE, MMM d"),
      );

      expect(formattedDates).toEqual([
        "Mon, Jan 5",
        "Tue, Jan 6",
        "Wed, Jan 7",
        "Thu, Jan 8",
        "Fri, Jan 9",
        "Sat, Jan 10",
        "Sun, Jan 11",
      ]);
    });

    it("should format 2026-01-06 as Tue, Jan 6 (not Jan 5)", () => {
      const day = createMockDaySummary({ business_date: "2026-01-06" });
      const formatted = formatBusinessDate(day.business_date, "EEE, MMM d");

      expect(formatted).toBe("Tue, Jan 6");
      expect(formatted).not.toContain("Jan 5"); // Bug would show Jan 5
    });

    it("should handle week spanning month boundary", () => {
      const crossMonthWeek: MockDaySummary[] = [
        createMockDaySummary({ business_date: "2026-01-29" }),
        createMockDaySummary({ business_date: "2026-01-30" }),
        createMockDaySummary({ business_date: "2026-01-31" }),
        createMockDaySummary({ business_date: "2026-02-01" }),
        createMockDaySummary({ business_date: "2026-02-02" }),
      ];

      const formattedDates = crossMonthWeek.map((day) =>
        formatBusinessDate(day.business_date, "EEE, MMM d"),
      );

      expect(formattedDates[2]).toBe("Sat, Jan 31");
      expect(formattedDates[3]).toBe("Sun, Feb 1");
    });
  });
});

// ============================================================================
// MONTHLY PAGE INTEGRATION TESTS
// ============================================================================

describe("RPD-INT: Monthly Reports Page Date Integration", () => {
  describe("RPD-INT-004: Daily Breakdown Date Formatting (Bug Fix Verification)", () => {
    /**
     * Verifies the fix for monthly/page.tsx:331
     * Daily breakdown table must show correct dates
     */
    it("should format business dates correctly for monthly breakdown", () => {
      // First 5 days of January
      const monthData: MockDaySummary[] = [
        createMockDaySummary({ business_date: "2026-01-01" }),
        createMockDaySummary({ business_date: "2026-01-02" }),
        createMockDaySummary({ business_date: "2026-01-03" }),
        createMockDaySummary({ business_date: "2026-01-04" }),
        createMockDaySummary({ business_date: "2026-01-05" }),
      ];

      const formattedDates = monthData.map((day) =>
        formatBusinessDate(day.business_date, "EEE, MMM d"),
      );

      expect(formattedDates[0]).toBe("Thu, Jan 1");
      expect(formattedDates[4]).toBe("Mon, Jan 5");
    });

    it("should format dates across full month correctly", () => {
      // Generate all days of January
      const janDates = generateCalendarDates(2026, 0);
      const monthData = janDates.map((date) =>
        createMockDaySummary({ business_date: date }),
      );

      monthData.forEach((day, index) => {
        const formatted = formatBusinessDate(day.business_date, "EEE, MMM d");
        const expectedDay = index + 1;

        // The formatted string should contain the correct day number
        expect(formatted).toContain(String(expectedDay));
        expect(formatted).not.toContain(String(expectedDay - 1)); // Bug check
      });
    });

    it("should handle year boundary in monthly view", () => {
      const yearEndDays: MockDaySummary[] = [
        createMockDaySummary({ business_date: "2025-12-30" }),
        createMockDaySummary({ business_date: "2025-12-31" }),
      ];

      const formattedDates = yearEndDays.map((day) =>
        formatBusinessDate(day.business_date, "EEE, MMM d"),
      );

      expect(formattedDates[0]).toBe("Tue, Dec 30");
      expect(formattedDates[1]).toBe("Wed, Dec 31");
    });
  });
});

// ============================================================================
// CROSS-PAGE SECURITY TESTS
// ============================================================================

describe("RPD-INT: Report Pages Security Integration", () => {
  describe("RPD-INT-005: XSS Prevention (SEC-004)", () => {
    it("should safely handle malicious business_date input", () => {
      const maliciousSummary = createMockDaySummary({
        business_date: "<script>alert('xss')</script>",
      });

      // formatBusinessDate returns original string for invalid input
      // React will escape this when rendering
      const formatted = formatBusinessDate(
        maliciousSummary.business_date,
        "EEE, MMM d",
      );

      // Should not be processed as a valid date
      expect(formatted).toBe("<script>alert('xss')</script>");

      // extractDayFromBusinessDate returns null for invalid
      const dayNumber = extractDayFromBusinessDate(
        maliciousSummary.business_date,
      );
      expect(dayNumber).toBe(null);
    });

    it("should handle SQL injection attempts in date field", () => {
      const sqlInjectionDate = "2026-01-06'; DROP TABLE day_summaries;--";

      expect(isValidBusinessDate(sqlInjectionDate)).toBe(false);
      expect(extractDayFromBusinessDate(sqlInjectionDate)).toBe(null);
    });
  });

  describe("RPD-INT-006: Input Validation (SEC-014)", () => {
    it("should handle null/undefined business_date gracefully", () => {
      const nullSummary = createMockDaySummary({
        business_date: null as unknown as string,
      });
      const undefinedSummary = createMockDaySummary({
        business_date: undefined as unknown as string,
      });

      expect(formatBusinessDate(nullSummary.business_date, "EEE, MMM d")).toBe(
        "—",
      );
      expect(
        formatBusinessDate(undefinedSummary.business_date, "EEE, MMM d"),
      ).toBe("—");

      expect(extractDayFromBusinessDate(nullSummary.business_date)).toBe(null);
      expect(extractDayFromBusinessDate(undefinedSummary.business_date)).toBe(
        null,
      );
    });

    it("should handle empty string business_date", () => {
      const emptySummary = createMockDaySummary({ business_date: "" });

      expect(formatBusinessDate(emptySummary.business_date, "EEE, MMM d")).toBe(
        "—",
      );
      expect(extractDayFromBusinessDate(emptySummary.business_date)).toBe(null);
    });

    it("should handle wrong date format gracefully", () => {
      const wrongFormatSummary = createMockDaySummary({
        business_date: "01-06-2026", // US format instead of ISO
      });

      // Returns original string for display
      const formatted = formatBusinessDate(
        wrongFormatSummary.business_date,
        "EEE, MMM d",
      );
      expect(formatted).toBe("01-06-2026");

      // Returns null for extraction
      const dayNumber = extractDayFromBusinessDate(
        wrongFormatSummary.business_date,
      );
      expect(dayNumber).toBe(null);
    });
  });
});

// ============================================================================
// END-TO-END DATA FLOW TESTS
// ============================================================================

describe("RPD-INT: Report Pages End-to-End Data Flow", () => {
  describe("RPD-INT-007: Complete Data Transformation Pipeline", () => {
    it("should process API response to display-ready format", () => {
      // Simulate API response
      const apiResponse: MockDaySummary[] = [
        {
          business_date: "2026-01-06",
          net_sales: 1500.0,
          transaction_count: 45,
          shift_count: 3,
          variance_amount: -5.5,
        },
        {
          business_date: "2026-01-07",
          net_sales: 1800.0,
          transaction_count: 52,
          shift_count: 3,
          variance_amount: 2.25,
        },
      ];

      // Transform for weekly/monthly table display
      const tableData = apiResponse.map((day) => ({
        displayDate: formatBusinessDate(day.business_date, "EEE, MMM d"),
        isValidDate: isValidBusinessDate(day.business_date),
        ...day,
      }));

      expect(tableData[0].displayDate).toBe("Tue, Jan 6");
      expect(tableData[0].isValidDate).toBe(true);
      expect(tableData[1].displayDate).toBe("Wed, Jan 7");
      expect(tableData[1].isValidDate).toBe(true);
    });

    it("should process calendar grid dates for daily page", () => {
      // Simulate calendar date generation as done in daily/page.tsx
      const calendarDates = generateCalendarDates(2026, 0);

      // Transform for calendar display
      const calendarCells = calendarDates.map((date) => ({
        dateString: date,
        dayNumber: extractDayFromBusinessDate(date) ?? 1,
        isValid: isValidBusinessDate(date),
      }));

      // Verify first week
      expect(calendarCells[0].dayNumber).toBe(1);
      expect(calendarCells[5].dayNumber).toBe(6); // The bug case
      expect(calendarCells[6].dayNumber).toBe(7);

      // All dates should be valid
      calendarCells.forEach((cell) => {
        expect(cell.isValid).toBe(true);
      });
    });
  });

  describe("RPD-INT-008: Consistency Across Report Types", () => {
    it("should format same date identically across all report pages", () => {
      const testDate = "2026-01-06";

      // Weekly page format
      const weeklyFormat = formatBusinessDate(testDate, "EEE, MMM d");

      // Monthly page format (same as weekly)
      const monthlyFormat = formatBusinessDate(testDate, "EEE, MMM d");

      // Daily page day extraction
      const dailyDayNumber = extractDayFromBusinessDate(testDate);

      // All should show day 6
      expect(weeklyFormat).toBe("Tue, Jan 6");
      expect(monthlyFormat).toBe("Tue, Jan 6");
      expect(dailyDayNumber).toBe(6);

      // Cross-page consistency
      expect(weeklyFormat).toBe(monthlyFormat);
      expect(weeklyFormat).toContain(String(dailyDayNumber));
    });
  });
});
